/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package bubt_rms.Panels;

/**
 *
 * @author islam
 */
public class Inventory extends javax.swing.JPanel {

    /**
     * Creates new form Inventory
     */
    public Inventory() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        Item_box = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        Quan_txt = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        Unit_Txt = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        Exp_Txt = new javax.swing.JTextField();
        Update_btn = new javax.swing.JButton();
        ClearBtn = new javax.swing.JButton();
        Add_Btn = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setBackground(new java.awt.Color(204, 0, 0));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Cafe Francoise", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 0));
        jLabel1.setText("Quantity");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, -1, -1));

        Item_box.setBackground(new java.awt.Color(255, 51, 0));
        Item_box.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Potato", "Chedder Cheese Slices", "Item 3", "Item 4" }));
        Item_box.setSelectedItem(jTable1);
        Item_box.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Item_boxActionPerformed(evt);
            }
        });
        add(Item_box, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 60, 400, 30));

        jLabel2.setFont(new java.awt.Font("Cafe Francoise", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 0));
        jLabel2.setText("Name of Item :");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, -1, -1));

        Quan_txt.setBackground(new java.awt.Color(255, 51, 0));
        add(Quan_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 120, 400, 30));

        jLabel3.setFont(new java.awt.Font("Cafe Francoise", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 0));
        jLabel3.setText("Unit");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, -1, -1));

        Unit_Txt.setBackground(new java.awt.Color(255, 51, 0));
        add(Unit_Txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 180, 400, 30));

        jLabel4.setFont(new java.awt.Font("Cafe Francoise", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 0));
        jLabel4.setText("Expiry Date");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, -1, -1));

        Exp_Txt.setBackground(new java.awt.Color(255, 51, 0));
        add(Exp_Txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 240, 400, 30));

        Update_btn.setBackground(new java.awt.Color(102, 0, 0));
        Update_btn.setFont(new java.awt.Font("Cafe Francoise", 0, 18)); // NOI18N
        Update_btn.setForeground(new java.awt.Color(255, 204, 0));
        Update_btn.setText("Update");
        Update_btn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Update_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Update_btnActionPerformed(evt);
            }
        });
        add(Update_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 320, 190, -1));

        ClearBtn.setBackground(new java.awt.Color(102, 0, 0));
        ClearBtn.setFont(new java.awt.Font("Cafe Francoise", 0, 18)); // NOI18N
        ClearBtn.setForeground(new java.awt.Color(255, 204, 0));
        ClearBtn.setText("Clear");
        ClearBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ClearBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearBtnActionPerformed(evt);
            }
        });
        add(ClearBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 320, 190, -1));

        Add_Btn.setBackground(new java.awt.Color(102, 0, 0));
        Add_Btn.setFont(new java.awt.Font("Cafe Francoise", 0, 18)); // NOI18N
        Add_Btn.setForeground(new java.awt.Color(255, 204, 0));
        Add_Btn.setText("Add Item");
        Add_Btn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Add_Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Add_BtnActionPerformed(evt);
            }
        });
        add(Add_Btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 60, 460, -1));

        jPanel2.setBackground(new java.awt.Color(204, 0, 0));

        jTable1.setBackground(new java.awt.Color(204, 0, 0));
        jTable1.setFont(new java.awt.Font("Cafe Francoise", 0, 14)); // NOI18N
        jTable1.setForeground(new java.awt.Color(255, 255, 0));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Name of Item", "Quantity", "Unit", "Expiry Date"
            }
        ));
        jTable1.setGridColor(new java.awt.Color(255, 0, 51));
        jTable1.setSelectionBackground(new java.awt.Color(255, 51, 0));
        jTable1.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTable1);

        jPanel2.add(jScrollPane1);

        add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 97, -1, 450));
    }// </editor-fold>//GEN-END:initComponents

    private void Update_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Update_btnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Update_btnActionPerformed

    private void ClearBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ClearBtnActionPerformed

    private void Add_BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Add_BtnActionPerformed
        // TODO add your handling code here:
        this.remove(Item_box);
        this.remove(Update_btn);
        javax.swing.JTextField AddItem_name = new javax.swing.JTextField();
        AddItem_name.setBackground(new java.awt.Color(255, 51, 0));
        //new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 60, 400, 30)
        
        this.add(AddItem_name,new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 60, 400, 30));
        
        javax.swing.JButton AddItem_btn = new javax.swing.JButton();
         AddItem_btn.setBackground(new java.awt.Color(102, 0, 0));
        AddItem_btn.setFont(new java.awt.Font("Cafe Francoise", 0, 18)); // NOI18N
        AddItem_btn.setForeground(new java.awt.Color(255, 204, 0));
        AddItem_btn.setText("Add");
        AddItem_btn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        AddItem_btn.addActionListener((java.awt.event.ActionEvent evt1) -> {
            Additem_BtnActionPerformed(evt1);
        });
        this.revalidate();
        
    }//GEN-LAST:event_Add_BtnActionPerformed

    private void Item_boxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Item_boxActionPerformed
        
        
        
    }//GEN-LAST:event_Item_boxActionPerformed
    private void Additem_BtnActionPerformed(java.awt.event.ActionEvent evt){
        //INSERT INTO `inventory` (`Inv_ID`, `Inv_Name`, `Inv_Quantity`, `Inv_Unit`, `Expiry_date`) VALUES ('1', 'Potato', '10', 'Kg', '2024-12-25');
        this.remove(this);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Add_Btn;
    private javax.swing.JButton ClearBtn;
    private javax.swing.JTextField Exp_Txt;
    private javax.swing.JComboBox<String> Item_box;
    private javax.swing.JTextField Quan_txt;
    private javax.swing.JTextField Unit_Txt;
    private javax.swing.JButton Update_btn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
