/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package bubt_rms;

import java.awt.Component;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.HeadlessException;
import java.awt.Shape;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.awt.geom.RoundRectangle2D;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author islam
 */
public class LoginScreen extends javax.swing.JFrame {

    

    /**
     * Creates new form LoginScreen
     */
    public LoginScreen() {
        initComponents();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        EmailTextField = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        PasswordTextField1 = new javax.swing.JPasswordField();
        jPanel10 = new javax.swing.JPanel();
        jCheckBox2 = new javax.swing.JCheckBox();
        jButton2 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 215, 0));
        jPanel1.setName(""); // NOI18N
        jPanel1.setPreferredSize(new java.awt.Dimension(400, 550));

        jPanel3.setBackground(new java.awt.Color(255, 215, 0));
        jPanel3.setPreferredSize(new java.awt.Dimension(400, 100));

        jLabel1.setFont(new java.awt.Font("Cafe Francoise", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(101, 49, 14));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("LOGIN");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.add(jPanel3);

        jPanel4.setBackground(new java.awt.Color(255, 215, 0));
        jPanel4.setPreferredSize(new java.awt.Dimension(400, 100));

        jButton1.setBackground(new java.awt.Color(252, 157, 0));
        jButton1.setFont(new java.awt.Font("Cafe Francoise", 0, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(101, 49, 14));
        jButton1.setText("CHANGE PASSWORD");
        jButton1.setAlignmentY(0.0F);
        jButton1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.setPreferredSize(new java.awt.Dimension(350, 46));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton1);

        jPanel1.add(jPanel4);

        jPanel5.setBackground(new java.awt.Color(255, 215, 0));
        jPanel5.setPreferredSize(new java.awt.Dimension(400, 250));

        jPanel8.setBackground(new java.awt.Color(255, 215, 0));
        jPanel8.setPreferredSize(new java.awt.Dimension(350, 70));
        jPanel8.setLayout(new java.awt.BorderLayout(3, 3));

        jLabel5.setFont(new java.awt.Font("Cafe Francoise", 0, 18)); // NOI18N
        jLabel5.setText("User Name");
        jLabel5.setAlignmentX(0.5F);
        jLabel5.setPreferredSize(new java.awt.Dimension(0, 25));
        jPanel8.add(jLabel5, java.awt.BorderLayout.PAGE_START);

        EmailTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                EmailTextFieldKeyPressed(evt);
            }
        });
        jPanel8.add(EmailTextField, java.awt.BorderLayout.CENTER);

        jPanel5.add(jPanel8);

        jPanel6.setBackground(new java.awt.Color(255, 215, 0));
        jPanel6.setPreferredSize(new java.awt.Dimension(350, 70));
        jPanel6.setLayout(new java.awt.BorderLayout(3, 3));

        jLabel3.setFont(new java.awt.Font("Cafe Francoise", 0, 18)); // NOI18N
        jLabel3.setText("password");
        jLabel3.setAlignmentX(0.5F);
        jLabel3.setInheritsPopupMenu(false);
        jLabel3.setPreferredSize(new java.awt.Dimension(0, 25));
        jPanel6.add(jLabel3, java.awt.BorderLayout.PAGE_START);

        PasswordTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                PasswordTextField1KeyPressed(evt);
            }
        });
        jPanel6.add(PasswordTextField1, java.awt.BorderLayout.CENTER);

        jPanel5.add(jPanel6);

        jPanel10.setBackground(new java.awt.Color(255, 215, 0));
        jPanel10.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel10.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEADING));

        jCheckBox2.setBackground(new java.awt.Color(255, 215, 0));
        jCheckBox2.setText("Remember Me");
        jCheckBox2.setPreferredSize(new java.awt.Dimension(350, 20));
        jCheckBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox2ActionPerformed(evt);
            }
        });
        jPanel10.add(jCheckBox2);

        jPanel5.add(jPanel10);

        jButton2.setBackground(new java.awt.Color(252, 157, 0));
        jButton2.setFont(new java.awt.Font("Cafe Francoise", 0, 24)); // NOI18N
        jButton2.setForeground(new java.awt.Color(101, 49, 14));
        jButton2.setText("Submit");
        jButton2.setAlignmentY(0.0F);
        jButton2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton2.setPreferredSize(new java.awt.Dimension(350, 46));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton2);

        jPanel1.add(jPanel5);

        jPanel2.setBackground(new java.awt.Color(252, 198, 16));
        jPanel2.setMaximumSize(new java.awt.Dimension(0, 0));
        jPanel2.setMinimumSize(new java.awt.Dimension(0, 0));
        jPanel2.setPreferredSize(new java.awt.Dimension(200, 430));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Cheezy3.png"))); // NOI18N
        jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 509, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 509, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jButton1ActionPerformed
    private void makeFrameFullSize(javax.swing.JFrame aFrame) {
            Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
            aFrame.setSize(screenSize.width/2, screenSize.height/2);
        }
    
     void LoginCall(String usr, String pswd){
        boolean flag = false;
        try{
            Class.forName("java.sql.Driver");
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/cheezyrms_bubt","root","");
            Statement stmt = conn.createStatement();
            String qrry = "select * from user_conf where UserName=\"" + usr +"\" and Password=\"" + pswd + "\";";
            ResultSet rs = stmt.executeQuery(qrry);
            while(rs.next()){
               flag=true;
            }
                if(flag){
                    Statement stmt2 = conn.createStatement();
                    String qrry2 = "select * from user_conf where UserName=\"" + usr +"\" and Password=\"" + pswd + "\" and Is_admin = \"1\";";
                    ResultSet rs2 = stmt2.executeQuery(qrry2);
                    
                    System.out.print(qrry);
                    boolean flag2 = false;
                    while(rs2.next()){
                        flag2 = true;
                    }
                    if(flag2){
                    this.dispose();
                    MainWindow aframe = new MainWindow();
                    aframe.setVisible(true);
                    }
                    else
                    {
                        this.dispose();
                        MainWindow_user aframe = new MainWindow_user();
                        aframe.setVisible(true);
                    }
                }
                else{
                     JOptionPane.showMessageDialog(null, "Invalid User-Name or Password");
                     System.out.print(qrry);
                }
            
        }catch(HeadlessException | ClassNotFoundException | SQLException ex){
            JOptionPane.showMessageDialog(null,"Error in Connectivity "+ex);
        }
    }
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        String UserName = new String(EmailTextField.getText());
        String pass = new String(PasswordTextField1.getPassword());
        LoginCall(UserName, pass);
//        if("Rummon".equals(EmailTextField.getText()) && "12345".equals(pass)){
//            
//            this.dispose();
//            MainWindow_user aframe = new MainWindow_user();
//            aframe.setVisible(true);
//                
//            
//        }
//        else if("Admin".equals(EmailTextField.getText()) && "21213".equals(pass))
//        {
//            this.dispose();
//            MainWindow aframe = new MainWindow();
//            aframe.setVisible(true);
//        }
//        else{
//            
//             JOptionPane.showMessageDialog(new javax.swing.JFrame(),
//    "Failed to Login",
//    "Unsuccessful log in",
//    JOptionPane.PLAIN_MESSAGE);
//        }


    }//GEN-LAST:event_jButton2ActionPerformed

    private void jCheckBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox2ActionPerformed

    private void EmailTextFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_EmailTextFieldKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()== KeyEvent.VK_ENTER){
            PasswordTextField1.requestFocus();
        }
    }//GEN-LAST:event_EmailTextFieldKeyPressed

    private void PasswordTextField1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PasswordTextField1KeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            jButton2ActionPerformed(null);
        }
    }//GEN-LAST:event_PasswordTextField1KeyPressed
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField EmailTextField;
    private javax.swing.JPasswordField PasswordTextField1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel8;
    // End of variables declaration//GEN-END:variables
    public class roundedtxtField extends javax.swing.JTextField{
     private Shape shape;
    public roundedtxtField(int size) {
        super(size);
        setOpaque(false); // As suggested by @AVD in comment.
    }
     @Override
    protected void paintComponent(Graphics g) {
         g.setColor(getBackground());
         g.fillRoundRect(0, 0, getWidth()-1, getHeight()-1, 15, 15);
         super.paintComponent(g);
    }
     @Override
    protected void paintBorder(Graphics g) {
         g.setColor(getForeground());
         g.drawRoundRect(0, 0, getWidth()-1, getHeight()-1, 15, 15);
    }
     @Override
    public boolean contains(int x, int y) {
         if (shape == null || !shape.getBounds().equals(getBounds())) {
             shape = new RoundRectangle2D.Float(0, 0, getWidth()-1, getHeight()-1, 15, 15);
         }
         return shape.contains(x, y);
    }
    
    
    }
}

